Cargamos las librerias

In [ ]:
# ============================================================
# CELDA 1 - IMPORTAR LIBRERÍAS
# ============================================================

import pandas as pd
import numpy as np
import os

In [ ]:
# ============================================================
# CELDA 2 - MONTAR GOOGLE DRIVE
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# ============================================================
# CELDA 3 - DEFINIR RUTA DEL DATASET
# ============================================================

# Ajusta esta ruta a tu carpeta real de Drive
ruta_dataset = "/content/drive/MyDrive/PROYECTO TFM IA_BG_E1/CLUSTERING/datasets/data_v01_clustering_ventas.csv"

# Comprobamos si el archivo existe
if os.path.exists(ruta_dataset):
    print("Archivo encontrado correctamente.")
else:
    print("ERROR: No se encontró el archivo. Revisa la ruta.")

Archivo encontrado correctamente.

In [ ]:
# ============================================================
# CELDA 4 - CARGAR DATASET
# ============================================================

df = pd.read_csv(ruta_dataset, encoding="ISO-8859-1")

print("Dataset cargado correctamente.")
print("Filas y columnas:", df.shape)

display(df.head())

Dataset cargado correctamente.
Filas y columnas: (522010, 22)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceDay,InvoiceMonth,...,DayOfWeek,IsUk,TotalPrice,IsWeekend,Sales_Lag_1,Sales_Lag_7,Sales_Mean_7,Sales_Mean_30,Trend_Lag1_vs_Lag7,DailyTotal
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,1,12,...,2,1,15.30,0,NaN,NaN,NaN,NaN,NaN,57442.33
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,15.30,NaN,NaN,NaN,NaN,57442.33
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,1,12,...,2,1,22.00,0,20.34,NaN,NaN,NaN,NaN,57442.33
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,22.00,NaN,NaN,NaN,NaN,57442.33
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,20.34,NaN,NaN,NaN,NaN,57442.33

In [ ]:
# ============================================================
# CELDA 5 - EXPLORACIÓN INICIAL
# ============================================================

print("Información general del dataset:")
df.info()

print("\nPrimeras filas:")
display(df.head())

print("\nColumnas disponibles:")
print(df.columns.tolist())

Información general del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522010 entries, 0 to 522009
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   InvoiceNo           522010 non-null  int64
 1   StockCode           522010 non-null  object
 2   Description         522010 non-null  object
 3   Quantity            522010 non-null  int64
 4   InvoiceDate         522010 non-null  object
 5   UnitPrice           522010 non-null  float64
 6   CustomerID          390600 non-null  float64
 7   Country             522010 non-null  object
 8   InvoiceDay          522010 non-null  int64
 9   InvoiceMonth        522010 non-null  int64
 10  InvoiceYear         522010 non-null  int64
 11  InvoiceHour         522010 non-null  int64
 12  DayOfWeek           522010 non-null  int64
 13  IsUk                522010 non-null  int64
 14  TotalPrice          522010 non-null  float64
 15  IsWeekend           522010 non-null  int64
 16  Sales_Lag_1         522009 non-null  float64
 17  Sales_Lag_7         522003 non-null  float64
 18  Sales_Mean_7        522004 non-null  float64
 19  Sales_Mean_30       521981 non-null  float64
 20  Trend_Lag1_vs_Lag7  522003 non-null  float64
 21  DailyTotal          522010 non-null  float64
dtypes: float64(9), int64(9), object(4)
memory usage: 87.6+ MB

Primeras filas:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceDay,InvoiceMonth,...,DayOfWeek,IsUk,TotalPrice,IsWeekend,Sales_Lag_1,Sales_Lag_7,Sales_Mean_7,Sales_Mean_30,Trend_Lag1_vs_Lag7,DailyTotal
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,1,12,...,2,1,15.30,0,NaN,NaN,NaN,NaN,NaN,57442.33
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,15.30,NaN,NaN,NaN,NaN,57442.33
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,1,12,...,2,1,22.00,0,20.34,NaN,NaN,NaN,NaN,57442.33
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,22.00,NaN,NaN,NaN,NaN,57442.33
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,1,12,...,2,1,20.34,0,20.34,NaN,NaN,NaN,NaN,57442.33

Columnas disponibles:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'InvoiceDay', 'InvoiceMonth', 'InvoiceYear', 'InvoiceHour', 'DayOfWeek', 'IsUk', 'TotalPrice', 'IsWeekend', 'Sales_Lag_1', 'Sales_Lag_7', 'Sales_Mean_7', 'Sales_Mean_30', 'Trend_Lag1_vs_Lag7', 'DailyTotal']

In [ ]:
# ============================================================
# CELDA 6 - COMPROBAR NULOS INICIALES
# ============================================================

nulos = df.isnull().sum().sort_values(ascending=False)

print("Valores nulos por columna:")
display(nulos[nulos > 0])

print("\nPorcentaje de nulos por columna:")
porcentaje_nulos = (df.isnull().mean() * 100).round(2).sort_values(ascending=False)
display(porcentaje_nulos[porcentaje_nulos > 0])

Valores nulos por columna:

CustomerID            131410
Sales_Mean_30             29
Trend_Lag1_vs_Lag7         7
Sales_Lag_7                7
Sales_Mean_7               6
Sales_Lag_1                1
dtype: int64

Porcentaje de nulos por columna:

CustomerID       25.17
Sales_Mean_30     0.01
dtype: float64

In [ ]:
# ============================================================
# CELDA 7 - GUARDAR REFERENCIA INICIAL
# ============================================================

filas_iniciales = df.shape[0]
columnas_iniciales = df.shape[1]

print("Filas iniciales:", filas_iniciales)
print("Columnas iniciales:", columnas_iniciales)

Filas iniciales: 522010
Columnas iniciales: 22

In [ ]:
# ============================================================
# CELDA 8 - ELIMINAR CUSTOMERID NULOS
# ============================================================

filas_antes = df.shape[0]

df = df.dropna(subset=["CustomerID"]).copy()

filas_despues = df.shape[0]
filas_eliminadas_customer = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por CustomerID nulo:", filas_eliminadas_customer)
print("CustomerID nulos restantes:", df["CustomerID"].isnull().sum())

Filas antes: 522010
Filas después: 390600
Filas eliminadas por CustomerID nulo: 131410
CustomerID nulos restantes: 0

In [ ]:
# ============================================================
# CELDA 9 - ELIMINAR DESCRIPTION NULAS
# ============================================================

filas_antes = df.shape[0]

df = df.dropna(subset=["Description"]).copy()

filas_despues = df.shape[0]
filas_eliminadas_description = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por Description nula:", filas_eliminadas_description)
print("Description nulas restantes:", df["Description"].isnull().sum())

Filas antes: 390600
Filas después: 390600
Filas eliminadas por Description nula: 0
Description nulas restantes: 0

In [ ]:
# ============================================================
# CELDA 10 - ELIMINAR FACTURAS CANCELADAS
# ============================================================

# Las facturas canceladas suelen empezar por la letra C
facturas_canceladas = df["InvoiceNo"].astype(str).str.startswith("C").sum()

print("Facturas canceladas detectadas:", facturas_canceladas)

filas_antes = df.shape[0]

df = df[~df["InvoiceNo"].astype(str).str.startswith("C")].copy()

filas_despues = df.shape[0]
filas_eliminadas_canceladas = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por InvoiceNo cancelado:", filas_eliminadas_canceladas)
print("Facturas canceladas restantes:", df["InvoiceNo"].astype(str).str.startswith("C").sum())

Facturas canceladas detectadas: 0
Filas antes: 390600
Filas después: 390600
Filas eliminadas por InvoiceNo cancelado: 0
Facturas canceladas restantes: 0

In [ ]:
# ============================================================
# CELDA 11 - ELIMINAR QUANTITY <= 0
# ============================================================

# Quantity negativa indica devolución.
# Quantity igual a 0 no representa una compra real.

cantidad_invalida = (df["Quantity"] <= 0).sum()

print("Filas con Quantity <= 0 detectadas:", cantidad_invalida)

filas_antes = df.shape[0]

df = df[df["Quantity"] > 0].copy()

filas_despues = df.shape[0]
filas_eliminadas_quantity = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por Quantity <= 0:", filas_eliminadas_quantity)
print("Quantity <= 0 restantes:", (df["Quantity"] <= 0).sum())

Filas con Quantity <= 0 detectadas: 0
Filas antes: 390600
Filas después: 390600
Filas eliminadas por Quantity <= 0: 0
Quantity <= 0 restantes: 0

In [ ]:
# ============================================================
# CELDA 12 - ELIMINAR UNITPRICE <= 0
# ============================================================

# UnitPrice igual o menor que 0 no representa una venta económica válida.
# Esta limpieza evita distorsionar TotalPrice, Monetary y AverageOrderValue.

precio_invalido = (df["UnitPrice"] <= 0).sum()

print("Filas con UnitPrice <= 0 detectadas:", precio_invalido)

filas_antes = df.shape[0]

df = df[df["UnitPrice"] > 0].copy()

filas_despues = df.shape[0]
filas_eliminadas_unitprice = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por UnitPrice <= 0:", filas_eliminadas_unitprice)
print("UnitPrice <= 0 restantes:", (df["UnitPrice"] <= 0).sum())

Filas con UnitPrice <= 0 detectadas: 0
Filas antes: 390600
Filas después: 390600
Filas eliminadas por UnitPrice <= 0: 0
UnitPrice <= 0 restantes: 0

In [ ]:
# ============================================================
# CELDA 13 - CONVERTIR TIPOS DE DATOS
# ============================================================

# CustomerID es un identificador, no una variable numérica predictiva.
# Se convierte a string para evitar formatos como 17850.0.

df["CustomerID"] = df["CustomerID"].astype(int).astype(str)

# InvoiceDate debe estar en formato datetime para el feature engineering posterior.
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")

# Comprobación de fechas inválidas tras la conversión
fechas_invalidas = df["InvoiceDate"].isnull().sum()

print("Tipos convertidos correctamente.")
print("Fechas inválidas tras conversión:", fechas_invalidas)

print("\nTipo de CustomerID:", df["CustomerID"].dtype)
print("Tipo de InvoiceDate:", df["InvoiceDate"].dtype)

display(df[["CustomerID", "InvoiceDate"]].head())

Tipos convertidos correctamente.
Fechas inválidas tras conversión: 0

Tipo de CustomerID: object
Tipo de InvoiceDate: datetime64[ns]

  CustomerID InvoiceDate
0      17850  2010-12-01
1      17850  2010-12-01
2      17850  2010-12-01
3      17850  2010-12-01
4      17850  2010-12-01

In [ ]:
# ============================================================
# CELDA 14 - RECALCULAR TOTALPRICE Y VALIDAR IMPORTES
# ============================================================

# Recalculamos TotalPrice para asegurar coherencia después de la limpieza.
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

# Validamos importes nulos, negativos o cero.
totalprice_invalidos = (df["TotalPrice"] <= 0).sum()

print("Columna TotalPrice recalculada correctamente.")
print("Filas con TotalPrice <= 0 detectadas:", totalprice_invalidos)

# Si existieran importes no positivos, se eliminan.
filas_antes = df.shape[0]

df = df[df["TotalPrice"] > 0].copy()

filas_despues = df.shape[0]
filas_eliminadas_totalprice = filas_antes - filas_despues

print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas por TotalPrice <= 0:", filas_eliminadas_totalprice)
print("TotalPrice <= 0 restantes:", (df["TotalPrice"] <= 0).sum())

display(df[["Quantity", "UnitPrice", "TotalPrice"]].head())

Columna TotalPrice recalculada correctamente.
Filas con TotalPrice <= 0 detectadas: 0
Filas antes: 390600
Filas después: 390600
Filas eliminadas por TotalPrice <= 0: 0
TotalPrice <= 0 restantes: 0

   Quantity  UnitPrice  TotalPrice
0         6       2.55       15.30
1         6       3.39       20.34
2         8       2.75       22.00
3         6       3.39       20.34
4         6       3.39       20.34

In [ ]:
# ============================================================
# CELDA 15 - ELIMINAR COLUMNAS HEREDADAS DE REGRESIÓN
# ============================================================

columnas_regresion = [
    "Sales_Lag_1",
    "Sales_Lag_7",
    "Sales_Mean_7",
    "Sales_Mean_30",
    "sales_lag_1",
    "sales_lag_7",
    "rolling_mean_7",
    "rolling_mean_30",
    "DailyTotal",
    "daily_total",
    "Trend_Lag1_vs_Lag7",
    "trend_1_vs_7",
    "IsUK",
    "IsUk",
    "isUK",
    "is_UK",
    "DayOfWeek",
    "dayOfweek",
    "day_of_week",
    "IsWeekend",
    "is_weekend",
    "InvoiceDay",
    "InvoiceMonth",
    "InvoiceYear",
    "InvoiceHour"
]

columnas_a_borrar = [col for col in columnas_regresion if col in df.columns]

print("Columnas de regresión encontradas para borrar:")
print(columnas_a_borrar)

df = df.drop(columns=columnas_a_borrar)

print("\nColumnas eliminadas:", len(columnas_a_borrar))
print("Columnas restantes:", df.columns.tolist())

Columnas de regresión encontradas para borrar:
['Sales_Lag_1', 'Sales_Lag_7', 'Sales_Mean_7', 'Sales_Mean_30', 'DailyTotal', 'Trend_Lag1_vs_Lag7', 'IsUk', 'DayOfWeek', 'IsWeekend', 'InvoiceDay', 'InvoiceMonth', 'InvoiceYear', 'InvoiceHour']

Columnas eliminadas: 13
Columnas restantes: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'TotalPrice']

In [ ]:
# ============================================================
# CELDA 16 - ORDENAR COLUMNAS Y COMPROBACIÓN FINAL
# ============================================================

columnas_finales = [
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country",
    "TotalPrice"
]

# Verificamos que todas las columnas necesarias existen.
columnas_faltantes = [col for col in columnas_finales if col not in df.columns]

if columnas_faltantes:
    raise ValueError(f"Faltan columnas necesarias en el dataset: {columnas_faltantes}")

# Dejamos el dataset solo con las columnas finales necesarias.
df = df[columnas_finales].copy()

print("COMPROBACIÓN FINAL DEL DATASET LIMPIO")
print("-" * 60)

print("Filas finales:", df.shape[0])
print("Columnas finales:", df.shape[1])

print("\nNulos en CustomerID:", df["CustomerID"].isnull().sum())
print("Nulos en Description:", df["Description"].isnull().sum())
print("Nulos en InvoiceDate:", df["InvoiceDate"].isnull().sum())

print("\nQuantity <= 0:", (df["Quantity"] <= 0).sum())
print("UnitPrice <= 0:", (df["UnitPrice"] <= 0).sum())
print("TotalPrice <= 0:", (df["TotalPrice"] <= 0).sum())

print("\nFacturas canceladas restantes:", df["InvoiceNo"].astype(str).str.startswith("C").sum())

print("\nClientes únicos:", df["CustomerID"].nunique())
print("Facturas únicas:", df["InvoiceNo"].nunique())
print("Productos únicos:", df["StockCode"].nunique())
print("Países presentes:", df["Country"].nunique())

print("\nPeriodo temporal:")
print("Fecha mínima:", df["InvoiceDate"].min())
print("Fecha máxima:", df["InvoiceDate"].max())

print("\nTotalPrice:")
print("Media:", round(df["TotalPrice"].mean(), 2))
print("Mínimo real:", df["TotalPrice"].min())
print("Máximo:", round(df["TotalPrice"].max(), 2))

print("\nColumnas finales:")
print(df.columns.tolist())

COMPROBACIÓN FINAL DEL DATASET LIMPIO
------------------------------------------------------------
Filas finales: 390600
Columnas finales: 9

Nulos en CustomerID: 0
Nulos en Description: 0
Nulos en InvoiceDate: 0

Quantity <= 0: 0
UnitPrice <= 0: 0
TotalPrice <= 0: 0

Facturas canceladas restantes: 0

Clientes únicos: 4333
Facturas únicas: 18351
Productos únicos: 3659
Países presentes: 37

Periodo temporal:
Fecha mínima: 2010-12-01 00:00:00
Fecha máxima: 2011-12-09 00:00:00

TotalPrice:
Media: 21.65
Mínimo real: 0.001
Máximo: 38970.0

Columnas finales:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'TotalPrice']

In [ ]:
# ============================================================
# CELDA 17 - RESUMEN DE LIMPIEZA
# ============================================================

filas_finales = df.shape[0]
filas_eliminadas_totales = filas_iniciales - filas_finales

resumen_limpieza = pd.DataFrame({
    "Paso": [
        "Dataset inicial",
        "CustomerID nulos eliminados",
        "Description nulas eliminadas",
        "Invoices canceladas eliminadas",
        "Quantity <= 0 eliminadas",
        "UnitPrice <= 0 eliminadas",
        "TotalPrice <= 0 eliminadas",
        "Dataset final limpio"
    ],
    "Filas": [
        filas_iniciales,
        filas_eliminadas_customer,
        filas_eliminadas_description,
        filas_eliminadas_canceladas,
        filas_eliminadas_quantity,
        filas_eliminadas_unitprice,
        filas_eliminadas_totalprice,
        filas_finales
    ]
})

resumen_limpieza["Porcentaje sobre inicial"] = (
    resumen_limpieza["Filas"] / filas_iniciales * 100
).round(2)

display(resumen_limpieza)

print("Filas eliminadas totales:", filas_eliminadas_totales)
print("Porcentaje eliminado:", round(filas_eliminadas_totales / filas_iniciales * 100, 2), "%")
print("Porcentaje conservado:", round(filas_finales / filas_iniciales * 100, 2), "%")

                             Paso   Filas  Porcentaje sobre inicial
0                 Dataset inicial  522010                    100.00
1     CustomerID nulos eliminados  131410                     25.17
2    Description nulas eliminadas       0                      0.00
3  Invoices canceladas eliminadas       0                      0.00
4        Quantity <= 0 eliminadas       0                      0.00
5       UnitPrice <= 0 eliminadas       0                      0.00
6      TotalPrice <= 0 eliminadas       0                      0.00
7            Dataset final limpio  390600                     74.83

Filas eliminadas totales: 131410
Porcentaje eliminado: 25.17 %
Porcentaje conservado: 74.83 %

In [ ]:
# ============================================================
# CELDA 18 - VISTA FINAL DEL DATASET LIMPIO
# ============================================================

display(df.head())

print("Dimensiones finales:", df.shape)

print("\nColumnas finales:")
print(df.columns.tolist())

print("\nTipos de datos finales:")
display(df.dtypes)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850,United Kingdom,20.34

Dimensiones finales: (390600, 9)

Columnas finales:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'TotalPrice']

Tipos de datos finales:

InvoiceNo               int64
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID             object
Country                object
TotalPrice            float64
dtype: object

In [ ]:
# ============================================================
# CELDA 19 - GUARDAR DATASET LIMPIO EN DRIVE
# ============================================================

ruta_salida = "/content/drive/MyDrive/Colab Notebooks/data_v02_clustering_limpio_ramon_v2.csv"

df.to_csv(ruta_salida, index=False, encoding="utf-8-sig")

print("Dataset limpio guardado correctamente en:")
print(ruta_salida)

Dataset limpio guardado correctamente en:
/content/drive/MyDrive/Colab Notebooks/data_v02_clustering_limpio_ramon_v2.csv

In [ ]:
# ============================================================
# CELDA 20 - DESCARGAR DATASET LIMPIO A LOCAL
# ============================================================

from google.colab import files

df.to_csv("data_v02_clustering_limpio_ramon_v2.csv", index=False, encoding="utf-8-sig")
files.download("data_v02_clustering_limpio_ramon_v2.csv")

In [ ]:
# ============================================================
# CELDA 21 - LIBRERÍAS PARA DOCUMENTACIÓN VISUAL
# ============================================================

import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display, Markdown

In [ ]:
# ============================================================
# CELDA 22 - TABLA RESUMEN DE LIMPIEZA
# ============================================================

resumen_limpieza = pd.DataFrame({
    "Paso": [
        "Dataset inicial",
        "CustomerID nulos eliminados",
        "Description nulas eliminadas",
        "Invoices canceladas eliminadas",
        "Quantity <= 0 eliminadas",
        "UnitPrice <= 0 eliminadas",
        "Dataset final limpio"
    ],
    "Filas afectadas": [
        filas_iniciales,
        filas_eliminadas_customer,
        filas_eliminadas_description,
        filas_eliminadas_canceladas,
        filas_eliminadas_quantity,
        filas_eliminadas_unitprice,
        df.shape[0]
    ]
})

resumen_limpieza["Porcentaje sobre inicial"] = (
    resumen_limpieza["Filas afectadas"] / filas_iniciales * 100
).round(2)

display(resumen_limpieza)

                             Paso  Filas afectadas  Porcentaje sobre inicial
0                 Dataset inicial           522010                    100.00
1     CustomerID nulos eliminados           131410                     25.17
2    Description nulas eliminadas                0                      0.00
3  Invoices canceladas eliminadas                0                      0.00
4        Quantity <= 0 eliminadas                0                      0.00
5       UnitPrice <= 0 eliminadas                0                      0.00
6            Dataset final limpio           390600                     74.83

In [ ]:
# ============================================================
# CELDA 23 - GRÁFICO DE BARRAS: FILAS ELIMINADAS POR PASO
# ============================================================

df_eliminadas = pd.DataFrame({
    "Motivo": [
        "CustomerID nulo",
        "Description nula",
        "Invoice cancelada",
        "Quantity <= 0",
        "UnitPrice <= 0"
    ],
    "Filas eliminadas": [
        filas_eliminadas_customer,
        filas_eliminadas_description,
        filas_eliminadas_canceladas,
        filas_eliminadas_quantity,
        filas_eliminadas_unitprice
    ]
})

fig = px.bar(
    df_eliminadas,
    x="Motivo",
    y="Filas eliminadas",
    text="Filas eliminadas",
    title="Filas eliminadas durante la limpieza del dataset de clustering"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Motivo de eliminación",
    yaxis_title="Número de filas",
    uniformtext_minsize=8,
    uniformtext_mode="hide"
)

fig.show()

In [ ]:
# ============================================================
# CELDA 24 - PIE CHART: FILAS CONSERVADAS VS ELIMINADAS
# ============================================================

filas_finales = df.shape[0]
filas_eliminadas_totales = filas_iniciales - filas_finales

df_pie = pd.DataFrame({
    "Estado": ["Filas conservadas", "Filas eliminadas"],
    "Cantidad": [filas_finales, filas_eliminadas_totales]
})

fig = px.pie(
    df_pie,
    names="Estado",
    values="Cantidad",
    title="Proporción de filas conservadas y eliminadas tras la limpieza",
    hole=0.35
)

fig.update_traces(textinfo="percent+label+value")
fig.show()

In [ ]:
# ============================================================
# CELDA 25 CORREGIDA - TABLA DE VALIDACIÓN FINAL DEL DATASET
# ============================================================

validacion_final = pd.DataFrame({
    "Comprobación": [
        "CustomerID nulos",
        "Description nulas",
        "InvoiceDate nulas",
        "Quantity <= 0",
        "UnitPrice <= 0",
        "TotalPrice <= 0",
        "Invoices canceladas",
        "Clientes únicos",
        "Facturas únicas",
        "Productos únicos",
        "Países presentes",
        "Filas finales",
        "Columnas finales"
    ],
    "Resultado": [
        df["CustomerID"].isnull().sum(),
        df["Description"].isnull().sum(),
        df["InvoiceDate"].isnull().sum(),
        (df["Quantity"] <= 0).sum(),
        (df["UnitPrice"] <= 0).sum(),
        (df["TotalPrice"] <= 0).sum(),
        df["InvoiceNo"].astype(str).str.startswith("C").sum(),
        df["CustomerID"].nunique(),
        df["InvoiceNo"].nunique(),
        df["StockCode"].nunique(),
        df["Country"].nunique(),
        df.shape[0],
        df.shape[1]
    ]
})

display(validacion_final)

           Comprobación  Resultado
0      CustomerID nulos          0
1     Description nulas          0
2     InvoiceDate nulas          0
3         Quantity <= 0          0
4        UnitPrice <= 0          0
5       TotalPrice <= 0          0
6   Invoices canceladas          0
7       Clientes únicos       4333
8       Facturas únicas      18351
9      Productos únicos       3659
10     Países presentes         37
11        Filas finales     390600
12     Columnas finales          9

In [ ]:
# ============================================================
# CELDA 26 - GRÁFICO 3D INTERACTIVO DEL DATASET LIMPIO
# ============================================================

# Tomamos una muestra para visualización interactiva.
# Si el dataset tiene menos de 10.000 filas, se usa completo.
n_muestra = min(10000, len(df))
df_muestra_3d = df.sample(n=n_muestra, random_state=42).copy()

fig = px.scatter_3d(
    df_muestra_3d,
    x="Quantity",
    y="UnitPrice",
    z="TotalPrice",
    color="Country",
    hover_data=["InvoiceNo", "StockCode", "Description", "CustomerID"],
    title="Visualización 3D interactiva del dataset limpio: Quantity, UnitPrice y TotalPrice"
)

fig.update_layout(
    scene=dict(
        xaxis_title="Cantidad comprada",
        yaxis_title="Precio unitario",
        zaxis_title="Importe total"
    ),
    margin=dict(l=0, r=0, b=0, t=50)
)

fig.show()

In [ ]:
# ============================================================
# CELDA 27 - BOXPLOTS INTERACTIVOS DE VARIABLES ECONÓMICAS
# ============================================================

df_box = df[["Quantity", "UnitPrice", "TotalPrice"]].copy()

fig = px.box(
    df_box,
    y=["Quantity", "UnitPrice", "TotalPrice"],
    title="Distribución y valores extremos tras la limpieza"
)

fig.update_layout(
    yaxis_title="Valor",
    xaxis_title="Variable"
)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# ============================================================
# CELDA 28 - HISTOGRAMA INTERACTIVO DE TOTALPRICE
# ============================================================

# Para que el gráfico sea legible, se limita al percentil 99.
limite_p99 = df["TotalPrice"].quantile(0.99)

df_hist = df[df["TotalPrice"] <= limite_p99].copy()

fig = px.histogram(
    df_hist,
    x="TotalPrice",
    nbins=80,
    title="Distribución de TotalPrice tras limpieza, excluyendo valores por encima del percentil 99"
)

fig.update_layout(
    xaxis_title="TotalPrice",
    yaxis_title="Número de transacciones"
)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# ============================================================
# CELDA 29 - PIE CHART: PESO DE UK VS INTERNACIONAL
# ============================================================

df_geo = df.copy()
df_geo["Zona"] = np.where(df_geo["Country"] == "United Kingdom", "United Kingdom", "Internacional")

resumen_geo = df_geo["Zona"].value_counts().reset_index()
resumen_geo.columns = ["Zona", "Transacciones"]

fig = px.pie(
    resumen_geo,
    names="Zona",
    values="Transacciones",
    title="Distribución geográfica del dataset limpio: UK vs internacional",
    hole=0.35
)

fig.update_traces(textinfo="percent+label+value")
fig.show()

In [ ]:
# ============================================================
# CELDA 30 - TOP 10 PAÍSES POR TRANSACCIONES
# ============================================================

top_paises = df["Country"].value_counts().head(10).reset_index()
top_paises.columns = ["País", "Transacciones"]

fig = px.bar(
    top_paises,
    x="País",
    y="Transacciones",
    text="Transacciones",
    title="Top 10 países por número de transacciones tras limpieza"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="País",
    yaxis_title="Número de transacciones"
)

fig.show()