Creamos una instalación minima para trabajar con Colab

In [ ]:
# Instalación mínima para Google Colab
!pip install -q pandas numpy matplotlib seaborn scikit-learn joblib

Importamos todas las librerias y dependencias que nos pueden hacer falta en un primer momento

In [ ]:
#importamos librerias y dependencias y las configuraciones
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import joblib
import os

#opciones para la visualizacion de las tablas
pd.set_option('display.max_columns', None)
pd.set_option("display.width", 120)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

#configuracion de graficos
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

#gestion de warning
warnings.filterwarnings('ignore')

print("Configuración del entorno\n")
print(f"Pandas: {pd.__version__}")
print(f"Numpy: {np.__version__}")
print(f"Matplotlib: {plt.matplotlib.__version__}")
print(f"Seaborn: {sns.__version__}")

Configuración del entorno

Pandas: 2.2.2
Numpy: 2.0.2
Matplotlib: 3.10.0
Seaborn: 0.13.2

Para trabajar con el dataset, subimos una copia del original en la carpeta compartida de DRIVE dataset/original/data.csv, descargarla en local e ir subiendo a esa carpeta compartida las distintas versiones ya editadas en dataset/limpio_versiones/ con el formato data_persona_v01.csv y un comentario en dicord de lo que se ha hecho en esa version.

En el paso final de entrega, esta celda se cambiara por una carga directa desde la web de kaggle

In [ ]:
#descargar una copia del data en local y luego cargarla en el notebook
from google.colab import files
dataset = files.upload()

Saving data.csv to data.csv

Una vez subido desde el local cargamos el dataset en colab, mostramos las primeras filas para hacernos una idea.

In [ ]:
# cargamos el dataset y mostramos las primeras filas
try:
    nombre_archivo = list(dataset.keys())[0]
    df = pd.read_csv(nombre_archivo, encoding="cp1252")
    print(f"Archivo {nombre_archivo} cargado exitosamente.")
    display(df.head())
except FileNotFoundError:
    print(f"Error: No se encontró el archivo: {nombre_archivo}")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Archivo data.csv cargado exitosamente.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,"17,850.00",United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,"17,850.00",United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom

Vamos ha hacer una vista generar del dataset para poder analizarlo

In [ ]:
#Vista general del dataset

#Aqui mostramos las dimensiones de dataset
print("Dimensiones del dataset:")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

#Todos los nombres de las columnas.
print("\nNombres de las columnas:")
print(df.columns)

#Tambien mostramos las 5 primeras y ultimas 5 filas del dataset
print("\nPrimeras 5 filas del dataset:")
display(df.head())
print("\nUltimas 5 filas del dataset:")
display(df.tail())

#En esta parte mostramos los tipos de datos y estructura del dataset
print("\nTipos de datos y estructura del dataset:")
display(df.info())

#Hacemos un resumen estadistico
print("\nResumen estadístico del dataset:")
display(df.describe())

#Hacemos un resumen descriptivo
print("\nResumen descriptivo del dataset:")
display(df.describe(include='object'))

Dimensiones del dataset:
Filas: 541909
Columnas: 8

Nombres de las columnas:
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'], dtype='object')

Primeras 5 filas del dataset:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,"17,850.00",United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,"17,850.00",United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom

Ultimas 5 filas del dataset:

       InvoiceNo StockCode                      Description  Quantity      InvoiceDate  UnitPrice  CustomerID Country
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12  12/9/2011 12:50       0.85   12,680.00  France
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6  12/9/2011 12:50       2.10   12,680.00  France
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4  12/9/2011 12:50       4.15   12,680.00  France
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4  12/9/2011 12:50       4.15   12,680.00  France
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3  12/9/2011 12:50       4.95   12,680.00  France

Tipos de datos y estructura del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

None

Resumen estadístico del dataset:

        Quantity  UnitPrice  CustomerID
count 541,909.00 541,909.00  406,829.00
mean        9.55       4.61   15,287.69
std       218.08      96.76    1,713.60
min   -80,995.00 -11,062.06   12,346.00
25%         1.00       1.25   13,953.00
50%         3.00       2.08   15,152.00
75%        10.00       4.13   16,791.00
max    80,995.00  38,970.00   18,287.00

Resumen descriptivo del dataset:

       InvoiceNo StockCode                         Description       InvoiceDate         Country
count     541909    541909                              540455            541909          541909
unique     25900      4070                                4223             23260              38
top       573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER  10/31/2011 14:41  United Kingdom
freq        1114      2313                                2369              1114          495478

Después de tener una vista más generalizada del mismo, pasamos a un análisis más exaustivo.

In [ ]:
#Identificacion de valores nulos

null = df.isnull().sum()
porcentaje_null = (null / len(df)) * 100


#Mostramos
print("Valores nulos por columna:")
print(null)
print("\nPorcentaje de valores nulos por columna:")
print(porcentaje_null)

#tabla

df_nulos = pd.DataFrame({
    "Nulos": null,
    "Porcentaje (%)": porcentaje_null.round(2)
})

df_nulos = df_nulos[df_nulos["Nulos"] > 0]
df_nulos = df_nulos.sort_values(by="Nulos", ascending=False)

if not df_nulos.empty:
    print("Columnas con valores nulos (conteo y porcentaje):")
    display(df_nulos)
else:
    print("No se encontraron valores nulos en el DataFrame.")

total_columnas_con_nulos = df_nulos.shape[0]

print(f"\nNúmero de columnas con al menos un valor nulo: {total_columnas_con_nulos}")

if total_columnas_con_nulos > 0:
    columna_mas_afectada = df_nulos.index[0]
    nulos_max = df_nulos.iloc[0]["Nulos"]
    porcentaje_max = df_nulos.iloc[0]["Porcentaje (%)"]

    print("Columna más afectada por valores nulos:")
    print(f"- {columna_mas_afectada}: {int(nulos_max):,} nulos ({porcentaje_max:.2f}%)")

Como podemos ver tenemos un 25% de valores nulos nada más que en una colunma, pasamos a identificar los duplicados.

In [ ]:
#Identificar valores duplicados

duplicados = df.duplicated().sum()
porcentaje_duplicados = (duplicados / len(df)) * 100

print("\n--- Detección de filas duplicadas ---")
print(f"Número de filas duplicadas: {duplicados}")
print(f"Porcentaje de filas duplicadas: {porcentaje_duplicados:.2f}%")

if duplicados > 0:
    print("\nMostrando las primeras 10 filas involucradas en duplicados:")

    duplicados_ejemplo = (
        df[df.duplicated(keep=False)]
        .sort_values(by=df.columns.tolist())
        .head(10)
    )

    display(duplicados_ejemplo)
else:
    print("\nNo se encontraron filas duplicadas en el DataFrame.")

if duplicados > 0:
    print(
        "Se han detectado filas repetidas exactamente en todas sus columnas. "
        "\nEsto sugiere la posible existencia de registros redundantes que deberán "
        "revisarse antes de la fase de limpieza."
    )
else:
    print("\nInterpretación inicial:")
    print("No se han detectado duplicados exactos, por lo que no sería necesario tratarlos.")

Hacemos una copia del dataset en la variable **dfc** para poder trabajar en la limpieza y poder hacer comparaciones con el dataset original,
así en **df** tenemos el original y en **dfc** la copia trabajada

In [ ]:
#hacemos una copia del dataset original para trabajar con ella y hacer comparaciones mas adelante.
dfc = df.copy()

Celda para guardar y descargar el dataset

In [ ]:
dfc.to_csv("data_persona_nuevas_columnas_regresion_v01.csv", index=False)

from google.colab import files
files.download("data_persona_nuevas_columnas__regresion_v01.csv")