In [ ]:
# Instalación mínima para Google Colab
!pip install -q pandas numpy matplotlib seaborn scikit-learn joblib kagglehub

In [ ]:
#importamos librerias y dependencias y las configuraciones
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import joblib
import glob
import kagglehub
import os


#opciones para la visualizacion de las tablas
pd.set_option('display.max_columns', None)
pd.set_option("display.width", 120)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

#configuracion de graficos
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

#gestion de warning
warnings.filterwarnings('ignore')

print("Configuración del entorno\n")
print(f"Pandas: {pd.__version__}")
print(f"Numpy: {np.__version__}")
print(f"Matplotlib: {plt.matplotlib.__version__}")
print(f"Seaborn: {sns.__version__}")

Configuración del entorno

Pandas: 2.2.2
Numpy: 2.0.2
Matplotlib: 3.10.0
Seaborn: 0.13.2

Para trabajar con el dataset, lo más rápido es tener una copia del original en la carpeta compartida de DRIVE dataset/original/data.csv, descargarla en local e ir subiendo a esa carpeta compartida las distintas versiones ya editadas en dataset/limpio_versiones/ con el formato data_persona_v01.csv y un comentario en dicord de lo que se ha hecho en esa version.

In [ ]:
#para cargar el dataset lo mas sencillo es tener una copia master en drive y
#descargarla en local y luego cargarla en el notebook
from google.colab import files
dataset = files.upload()

Saving data.csv to data (1).csv

In [ ]:
# cargamos el dataset y mostramos las primeras filas
try:
    nombre_archivo = list(dataset.keys())[0]
    df = pd.read_csv(nombre_archivo, encoding="cp1252")
    print(f"Archivo {nombre_archivo} cargado exitosamente.")
    display(df.head())
except FileNotFoundError:
    print(f"Error: No se encontró el archivo: {nombre_archivo}")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Archivo data (1).csv cargado exitosamente.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,"17,850.00",United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,"17,850.00",United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom

In [ ]:
#Vista general del dataset

#Dimensiones de dataset
print("Dimensiones del dataset:")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

#Nombres de las columnas.
print("\nNombres de las columnas:")
print(df.columns)

#Primeras y ultimas 5 filas del dataset
print("\nPrimeras 5 filas del dataset:")
display(df.head())
print("\nUltimas 5 filas del dataset:")
display(df.tail())

#tipos de datos y estructura
print("\nTipos de datos y estructura del dataset:")
display(df.info())

#resumen estadistico
print("\nResumen estadístico y descriptivo del dataset:")
display(df.describe(include=['object', 'int64', 'float64']))

#resumen descriptivo
#print("\nResumen descriptivo del dataset:")
#display(df.describe(include=['object', 'int64', 'float64']))

Dimensiones del dataset:
Filas: 541909
Columnas: 8

Nombres de las columnas:
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'], dtype='object')

Primeras 5 filas del dataset:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,"17,850.00",United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,"17,850.00",United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom

Ultimas 5 filas del dataset:

       InvoiceNo StockCode                      Description  Quantity      InvoiceDate  UnitPrice  CustomerID Country
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12  12/9/2011 12:50       0.85   12,680.00  France
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6  12/9/2011 12:50       2.10   12,680.00  France
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4  12/9/2011 12:50       4.15   12,680.00  France
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4  12/9/2011 12:50       4.15   12,680.00  France
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3  12/9/2011 12:50       4.95   12,680.00  France

Tipos de datos y estructura del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

None

Resumen estadístico y descriptivo del dataset:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,"541,909.00",541909,"541,909.00","406,829.00",541909
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.55,NaN,4.61,"15,287.69",NaN
std,NaN,NaN,NaN,218.08,NaN,96.76,"1,713.60",NaN
min,NaN,NaN,NaN,"-80,995.00",NaN,"-11,062.06","12,346.00",NaN
25%,NaN,NaN,NaN,1.00,NaN,1.25,"13,953.00",NaN
50%,NaN,NaN,NaN,3.00,NaN,2.08,"15,152.00",NaN
75%,NaN,NaN,NaN,10.00,NaN,4.13,"16,791.00",NaN
max,NaN,NaN,NaN,"80,995.00",NaN,"38,970.00","18,287.00",NaN

In [ ]:
#Identificar valores duplicados

duplicados = df.duplicated().sum()
porcentaje_duplicados = (duplicados / len(df)) * 100

print("\n--- Detección de filas duplicadas ---")
print(f"Número de filas duplicadas: {duplicados}")
print(f"Porcentaje de filas duplicadas: {porcentaje_duplicados:.2f}%")

if duplicados > 0:
    print("\nMostrando las primeras 10 filas involucradas en duplicados:")

    duplicados_ejemplo = (
        df[df.duplicated(keep=False)]
        .sort_values(by=df.columns.tolist())
        .head(10)
    )

    display(duplicados_ejemplo)
else:
    print("\nNo se encontraron filas duplicadas en el DataFrame.")

if duplicados > 0:
    print(
        "Se han detectado filas repetidas exactamente en todas sus columnas. "
        "\nEsto sugiere la posible existencia de registros redundantes que deberán "
        "revisarse antes de la fase de limpieza."
    )
else:
    print("\nInterpretación inicial:")
    print("No se han detectado duplicados exactos, por lo que no sería necesario tratarlos.")

--- Detección de filas duplicadas ---
Número de filas duplicadas: 5268
Porcentaje de filas duplicadas: 0.97%

Mostrando las primeras 10 filas involucradas en duplicados:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,"17,908.00",United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,"17,908.00",United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,"17,908.00",United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,"17,908.00",United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,"17,908.00",United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,"17,908.00",United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,"17,908.00",United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,"17,908.00",United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,"17,920.00",United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,"17,920.00",United Kingdom

Se han detectado filas repetidas exactamente en todas sus columnas.
Esto sugiere la posible existencia de registros redundantes que deberán revisarse antes de la fase de limpieza.

In [ ]:
#hacemos una copia del dataset original para trabajar con ella y hacer comparaciones mas adelante.
dfc = df.copy()

In [ ]:
#borramos duplicados en una primera fase ya que sabemos seguro que no nos sirven
print(f"Dimensiones del DataFrame antes de eliminar duplicados: {dfc.shape}")
dfc.drop_duplicates(inplace=True)
print(f"Dimensiones del DataFrame después de eliminar duplicados: {dfc.shape}")

#mostramos cuantas filas duplicadas se han borrado
print(f"Filas duplicadas borradas: {len(df) - len(dfc)}")

Dimensiones del DataFrame antes de eliminar duplicados: (541909, 8)
Dimensiones del DataFrame después de eliminar duplicados: (536641, 8)
Filas duplicadas borradas: 5268

In [ ]:
#a partir de ahora trabajarenos con la copia dfc del dataset limpio de duplicados
#Identificacion de valores nulos

null = dfc.isnull().sum()
porcentaje_null = (null / len(dfc)) * 100


#Mostramos
print("Valores nulos por columna:")
print(null)
print("\nPorcentaje de valores nulos por columna:")
print(porcentaje_null)

#tabla

df_nulos = pd.DataFrame({
    "Nulos": null,
    "Porcentaje (%)": porcentaje_null.round(2)
})

df_nulos = df_nulos[df_nulos["Nulos"] > 0]
df_nulos = df_nulos.sort_values(by="Nulos", ascending=False)

if not df_nulos.empty:
    print("Columnas con valores nulos (conteo y porcentaje):")
    display(df_nulos)
else:
    print("No se encontraron valores nulos en el DataFrame.")

total_columnas_con_nulos = df_nulos.shape[0]

print(f"\nTotal de columnas con valores nulos: {total_columnas_con_nulos}")

Valores nulos por columna:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

Porcentaje de valores nulos por columna:
InvoiceNo      0.00
StockCode      0.00
Description    0.27
Quantity       0.00
InvoiceDate    0.00
UnitPrice      0.00
CustomerID    25.16
Country        0.00
dtype: float64
Columnas con valores nulos (conteo y porcentaje):

              Nulos  Porcentaje (%)
CustomerID   135037           25.16
Description    1454            0.27

Total de columnas con valores nulos: 2

In [ ]:
#mostrar todos los nulos de CustomerID
nulos_customer_id = dfc[dfc['CustomerID'].isnull()]
print(f"Número de registros con CustomerID nulo: {len(nulos_customer_id)}")
display(nulos_customer_id)

Número de registros con CustomerID nulo: 135037

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/9/2011 10:26,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,12/9/2011 10:26,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,12/9/2011 10:26,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,12/9/2011 10:26,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,12/9/2011 10:26,"1,714.17",NaN,United Kingdom

In [ ]:
#borrar nulos con mas de tres columnas nulas o cero

In [ ]:
# ==============================
# ANÁLISIS DE FILAS ANÓMALAS
# ==============================

# 1) Máscaras base
A = dfc['UnitPrice'] == 0
B = dfc['Quantity'] <= 0
C = dfc['CustomerID'].isnull()
D = dfc['Description'].isnull()

# 2) Tres opciones de filtrado
mask1 = (A & B) | (C & D)
mask2 = A & B & C & D
mask3 = A | (B & C & D)

# 3) Mostrar cuántas filas devuelve cada opción
print("RESULTADOS DE LAS 3 OPCIONES")
print(f"Opción 1 -> ((UnitPrice == 0) y (Quantity <= 0)) o ((CustomerID nulo) y (Description nula)): {mask1.sum()}")
print(f"Opción 2 -> (UnitPrice == 0) y (Quantity <= 0) y (CustomerID nulo) y (Description nula): {mask2.sum()}")
print(f"Opción 3 -> (UnitPrice == 0) o ((Quantity <= 0) y (CustomerID nulo) y (Description nula)): {mask3.sum()}")

# 4) Elegir qué opción analizar
# Cambia aquí: "opcion1", "opcion2" o "opcion3"
modo_analisis = "opcion3"

if modo_analisis == "opcion1":
    condiciones_especificas = mask1
    descripcion_modo = "((UnitPrice == 0) y (Quantity <= 0)) o ((CustomerID nulo) y (Description nula))"
elif modo_analisis == "opcion2":
    condiciones_especificas = mask2
    descripcion_modo = "(UnitPrice == 0) y (Quantity <= 0) y (CustomerID nulo) y (Description nula)"
elif modo_analisis == "opcion3":
    condiciones_especificas = mask3
    descripcion_modo = "(UnitPrice == 0) o ((Quantity <= 0) y (CustomerID nulo) y (Description nula))"
else:
    raise ValueError("modo_analisis debe ser: 'opcion1', 'opcion2' o 'opcion3'")

# 5) Subconjunto filtrado
filas_caso_especifico = dfc[condiciones_especificas].copy()

print("\n" + "="*70)
print(f"MODO DE ANÁLISIS SELECCIONADO: {modo_analisis}")
print(f"Lógica aplicada: {descripcion_modo}")
print(f"Número de registros encontrados: {len(filas_caso_especifico)}")

if filas_caso_especifico.empty:
    print("No se encontraron filas que cumplan con las condiciones específicas.")
else:
    # 6) Crear banderas de anomalía dentro del subconjunto filtrado
    filas_caso_especifico['anomalia_unitprice_0'] = filas_caso_especifico['UnitPrice'] == 0
    filas_caso_especifico['anomalia_quantity_le_0'] = filas_caso_especifico['Quantity'] <= 0
    filas_caso_especifico['anomalia_quantity_lt_0'] = filas_caso_especifico['Quantity'] < 0
    filas_caso_especifico['anomalia_quantity_eq_0'] = filas_caso_especifico['Quantity'] == 0
    filas_caso_especifico['anomalia_customerid_nulo'] = filas_caso_especifico['CustomerID'].isnull()
    filas_caso_especifico['anomalia_description_nula'] = filas_caso_especifico['Description'].isnull()

    # 7) Etiqueta exacta de combinación de anomalías
    def etiquetar_fila(row):
        etiquetas = []
        if row['anomalia_unitprice_0']:
            etiquetas.append("UnitPrice=0")
        if row['anomalia_quantity_le_0']:
            etiquetas.append("Quantity<=0")
        if row['anomalia_customerid_nulo']:
            etiquetas.append("CustomerID nulo")
        if row['anomalia_description_nula']:
            etiquetas.append("Description nula")
        return " + ".join(etiquetas) if etiquetas else "Sin anomalía"

    filas_caso_especifico['tipo_anomalia'] = filas_caso_especifico.apply(etiquetar_fila, axis=1)

    # 8) Resumen individual por anomalía
    resumen_individual = pd.DataFrame({
        'Métrica': [
            'Total filas filtradas',
            'UnitPrice = 0',
            'Quantity <= 0',
            'Quantity < 0 (devoluciones o ajustes)',
            'Quantity = 0',
            'CustomerID nulo',
            'Description nula',
            'UnitPrice = 0 y Quantity <= 0',
            'CustomerID nulo y Description nula',
            'Las 4 condiciones a la vez'
        ],
        'Cantidad': [
            len(filas_caso_especifico),
            filas_caso_especifico['anomalia_unitprice_0'].sum(),
            filas_caso_especifico['anomalia_quantity_le_0'].sum(),
            filas_caso_especifico['anomalia_quantity_lt_0'].sum(),
            filas_caso_especifico['anomalia_quantity_eq_0'].sum(),
            filas_caso_especifico['anomalia_customerid_nulo'].sum(),
            filas_caso_especifico['anomalia_description_nula'].sum(),
            (filas_caso_especifico['anomalia_unitprice_0'] & filas_caso_especifico['anomalia_quantity_le_0']).sum(),
            (filas_caso_especifico['anomalia_customerid_nulo'] & filas_caso_especifico['anomalia_description_nula']).sum(),
            (
                filas_caso_especifico['anomalia_unitprice_0'] &
                filas_caso_especifico['anomalia_quantity_le_0'] &
                filas_caso_especifico['anomalia_customerid_nulo'] &
                filas_caso_especifico['anomalia_description_nula']
            ).sum()
        ]
    })

    # 9) Resumen por combinaciones exactas
    resumen_combinaciones = (
        filas_caso_especifico['tipo_anomalia']
        .value_counts(dropna=False)
        .reset_index()
    )
    resumen_combinaciones.columns = ['Combinación exacta de anomalías', 'Cantidad']

    # 10) Mostrar resultados
    print("\nRESUMEN INDIVIDUAL DE ANOMALÍAS")
    display(resumen_individual)

    print("\nRESUMEN POR COMBINACIONES EXACTAS")
    display(resumen_combinaciones)

    print("\nPRIMERAS 20 FILAS DETECTADAS")
    display(
        filas_caso_especifico[
            [
                'InvoiceNo', 'StockCode', 'Description', 'Quantity',
                'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country',
                'tipo_anomalia'
            ]
        ].head(20)
    )

RESULTADOS DE LAS 3 OPCIONES
Opción 1 -> ((UnitPrice == 0) y (Quantity <= 0)) o ((CustomerID nulo) y (Description nula)): 1928
Opción 2 -> (UnitPrice == 0) y (Quantity <= 0) y (CustomerID nulo) y (Description nula): 862
Opción 3 -> (UnitPrice == 0) o ((Quantity <= 0) y (CustomerID nulo) y (Description nula)): 2510

======================================================================
MODO DE ANÁLISIS SELECCIONADO: opcion3
Lógica aplicada: (UnitPrice == 0) o ((Quantity <= 0) y (CustomerID nulo) y (Description nula))
Número de registros encontrados: 2510

RESUMEN INDIVIDUAL DE ANOMALÍAS

                                 Métrica  Cantidad
0                  Total filas filtradas      2510
1                          UnitPrice = 0      2510
2                          Quantity <= 0      1336
3  Quantity < 0 (devoluciones o ajustes)      1336
4                           Quantity = 0         0
5                        CustomerID nulo      2470
6                       Description nula      1454
7          UnitPrice = 0 y Quantity <= 0      1336
8     CustomerID nulo y Description nula      1454
9             Las 4 condiciones a la vez       862

RESUMEN POR COMBINACIONES EXACTAS

                     Combinación exacta de anomalías  Cantidad
0  UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...       862
1   UnitPrice=0 + CustomerID nulo + Description nula       592
2                      UnitPrice=0 + CustomerID nulo       542
3        UnitPrice=0 + Quantity<=0 + CustomerID nulo       474
4                                        UnitPrice=0        40

PRIMERAS 20 FILAS DETECTADAS

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,tipo_anomalia
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
1970,536545,21134,NaN,1,12/1/2010 14:32,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
1971,536546,22145,NaN,1,12/1/2010 14:33,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
1972,536547,37509,NaN,1,12/1/2010 14:33,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
1988,536550,85044,NaN,1,12/1/2010 14:34,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
2024,536552,20950,NaN,1,12/1/2010 14:34,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
2025,536553,37461,NaN,3,12/1/2010 14:35,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
2026,536554,84670,NaN,23,12/1/2010 14:35,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...
4348,536765,84952C,NaN,19,12/2/2010 14:43,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
6391,536941,22734,amazon,20,12/3/2010 12:08,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo
6392,536942,22139,amazon,15,12/3/2010 12:08,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo
7187,536995,35951,NaN,57,12/3/2010 15:29,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...
7191,536999,21421,NaN,110,12/3/2010 15:32,0.00,NaN,United Kingdom,UnitPrice=0 + CustomerID nulo + Description nula
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.00,NaN,United Kingdom,UnitPrice=0 + Quantity<=0 + CustomerID nulo + ...

In [ ]:
#borra todas las filas que cumplen la condicion 3 precio 0 o cantidad cero y customerid null y descripcion null
#Opción 3 -> (UnitPrice == 0) o ((Quantity <= 0) y (CustomerID nulo) y (Description nula)): 2510

condiciones_especificas = (dfc['UnitPrice'] == 0) | (
    (dfc['Quantity'] == 0) &
    (dfc['CustomerID'].isnull()) &
    (dfc['Description'].isnull())
)

dfc = dfc[~condiciones_especificas].copy()

print(f"Filas restantes: {len(dfc)}")

Filas restantes: 534131

In [ ]:
#muestra las primeras 20 filas del dataset
dfc.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,"17,850.00",United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,"17,850.00",United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,"17,850.00",United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,"17,850.00",United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,"17,850.00",United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,"17,850.00",United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,"17,850.00",United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,"13,047.00",United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,"13,047.00",United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,"13,047.00",United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,"13,047.00",United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,"13,047.00",United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,"13,047.00",United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,"13,047.00",United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,"13,047.00",United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,"13,047.00",United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,"13,047.00",United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,"13,047.00",United Kingdom

In [ ]:
print(f"Filas dataset limpio: {len(dfc)}")
print(f"Filas original: {len(df)}")
print(f'Filas borradas tras aplicar la regla 3 y la eliminacion de duplicados: {len(df) - len(dfc)}')

Filas dataset limpio: 534131
Filas original: 541909
Filas borradas tras aplicar la regla 3 y la eliminacion de duplicados: 7778

In [ ]:
#imprime todas las filas de dfc donde Quantity es menor que 0
filas_negativas = dfc[dfc['Quantity'] < 0]
print(f"Número de filas con Quantity < 0: {len(filas_negativas)}")

Número de filas con Quantity < 0: 9251

In [ ]:
# ============================================================
# FILAS CON VALORES MÁS ALTOS Y MÁS BAJOS
# ============================================================
dfc['TotalPrice'] = dfc['Quantity'] * dfc['UnitPrice']

columnas_mostrar = [
    'InvoiceNo', 'StockCode', 'Description', 'Quantity',
    'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'TotalPrice'
]

for col in ['Quantity', 'UnitPrice', 'TotalPrice']:
    print(f"\n{'='*80}")
    print(f"TOP 20 VALORES MÁS ALTOS EN {col}")
    print(f"{'='*80}")
    display(dfc.nlargest(20, col)[columnas_mostrar])

    print(f"\n{'='*80}")
    print(f"TOP 20 VALORES MÁS BAJOS EN {col}")
    print(f"{'='*80}")
    display(dfc.nsmallest(20, col)[columnas_mostrar])

================================================================================
TOP 20 VALORES MÁS ALTOS EN Quantity
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,"16,446.00",United Kingdom,"168,469.60"
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,"12,346.00",United Kingdom,"77,183.60"
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/2011 12:26,0.21,"12,901.00",United Kingdom,"1,008.00"
206121,554868,22197,SMALL POPCORN HOLDER,4300,5/27/2011 10:52,0.72,"13,135.00",United Kingdom,"3,096.00"
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2/22/2011 10:43,0.82,"18,087.00",United Kingdom,"3,202.92"
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,7/19/2011 17:04,0.06,"14,609.00",United Kingdom,191.16
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,1/11/2011 12:55,2.10,"15,749.00",United Kingdom,"6,539.40"
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,4/18/2011 13:20,2.10,"15,749.00",United Kingdom,"6,539.40"
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,11/2/2011 11:24,0.32,"16,308.00",United Kingdom,960.00
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,12/2/2010 17:38,0.18,"16,754.00",United Kingdom,518.40
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,8/4/2011 18:06,1.45,"12,931.00",United Kingdom,"4,176.00"
201149,554272,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2700,5/23/2011 13:08,0.42,"12,901.00",United Kingdom,"1,134.00"
80742,543057,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,2/3/2011 10:50,0.21,"16,333.00",United Kingdom,544.32
32671,539101,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,12/16/2010 10:35,0.94,"16,029.00",United Kingdom,"2,256.00"
87631,543669,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,2/11/2011 11:22,0.94,"16,029.00",United Kingdom,"2,256.00"
91772,544152,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,2400,2/16/2011 12:10,0.06,"14,609.00",United Kingdom,144.00
421601,573003,23084,RABBIT NIGHT LIGHT,2400,10/27/2011 12:11,2.08,"14,646.00",Netherlands,"4,992.00"
125282,547037,21967,PACK OF 12 SKULL TISSUES,2160,3/20/2011 10:37,0.25,"14,101.00",United Kingdom,540.00
437480,574294,21915,RED HARMONICA IN BOX,2100,11/3/2011 15:47,1.06,"16,333.00",United Kingdom,"2,226.00"
511421,579498,23084,RABBIT NIGHT LIGHT,2040,11/29/2011 15:52,1.79,"12,798.00",Japan,"3,651.60"

================================================================================
TOP 20 VALORES MÁS BAJOS EN Quantity
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/9/2011 9:27,2.08,"16,446.00",United Kingdom,"-168,469.60"
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1/18/2011 10:17,1.04,"12,346.00",United Kingdom,"-77,183.60"
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,12/2/2010 14:23,0.03,"15,838.00",United Kingdom,-280.80
160145,C550456,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,-3114,4/18/2011 13:08,2.10,"15,749.00",United Kingdom,"-6,539.40"
160144,C550456,21175,GIN + TONIC DIET METAL SIGN,-2000,4/18/2011 13:08,1.85,"15,749.00",United Kingdom,"-3,700.00"
160143,C550456,85123A,WHITE HANGING HEART T-LIGHT HOLDER,-1930,4/18/2011 13:08,2.55,"15,749.00",United Kingdom,"-4,921.50"
224419,C556522,22920,HERB MARKER BASIL,-1515,6/13/2011 11:21,0.55,"16,938.00",United Kingdom,-833.25
187609,C552995,M,Manual,-1350,5/12/2011 15:19,0.16,"18,133.00",United Kingdom,-216.00
160142,C550456,47566B,TEA TIME PARTY BUNTING,-1300,4/18/2011 13:08,2.55,"15,749.00",United Kingdom,"-3,315.00"
390544,C570556,20971,PINK BLUE FELT CRAFT TRINKET BOX,-1296,10/11/2011 11:10,1.06,"16,029.00",United Kingdom,"-1,373.76"
377448,C569552,15034,PAPER POCKET TRAVELING FAN,-1200,10/4/2011 17:44,0.07,"14,533.00",United Kingdom,-84.00
182728,C552568,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,-960,5/10/2011 12:04,0.21,"12,901.00",United Kingdom,-201.60
390543,C570556,22147,FELTCRAFT BUTTERFLY HEARTS,-840,10/11/2011 11:10,1.25,"16,029.00",United Kingdom,"-1,050.00"
304430,C563577,21877,HOME SWEET HOME MUG,-828,8/17/2011 15:06,1.06,"17,949.00",United Kingdom,-877.68
349750,C567527,23113,PANTRY CHOPPING BOARD,-756,9/21/2011 9:16,5.06,"17,450.00",United Kingdom,"-3,825.36"
108088,C545478,D,Discount,-720,3/3/2011 11:08,0.01,"16,422.00",United Kingdom,-7.20
390541,C570556,22273,FELTCRAFT DOLL MOLLY,-720,10/11/2011 11:10,2.30,"16,029.00",United Kingdom,"-1,656.00"
390547,C570556,22273,FELTCRAFT DOLL MOLLY,-720,10/11/2011 11:10,2.55,"16,029.00",United Kingdom,"-1,836.00"
414136,C572343,22102,MIRROR MOSAIC T-LIGHT HOLDER,-720,10/24/2011 10:40,0.39,"14,607.00",United Kingdom,-280.80
304432,C563577,21069,VINTAGE BILLBOARD TEA MUG,-701,8/17/2011 15:06,1.06,"17,949.00",United Kingdom,-743.06

================================================================================
TOP 20 VALORES MÁS ALTOS EN UnitPrice
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
222681,C556445,M,Manual,-1,6/10/2011 15:31,"38,970.00","15,098.00",United Kingdom,"-38,970.00"
524602,C580605,AMAZONFEE,AMAZON FEE,-1,12/5/2011 11:36,"17,836.46",NaN,United Kingdom,"-17,836.46"
43702,C540117,AMAZONFEE,AMAZON FEE,-1,1/5/2011 9:55,"16,888.02",NaN,United Kingdom,"-16,888.02"
43703,C540118,AMAZONFEE,AMAZON FEE,-1,1/5/2011 9:57,"16,453.71",NaN,United Kingdom,"-16,453.71"
15016,C537630,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:04,"13,541.33",NaN,United Kingdom,"-13,541.33"
15017,537632,AMAZONFEE,AMAZON FEE,1,12/7/2010 15:08,"13,541.33",NaN,United Kingdom,"13,541.33"
16356,C537651,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:49,"13,541.33",NaN,United Kingdom,"-13,541.33"
16232,C537644,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:34,"13,474.79",NaN,United Kingdom,"-13,474.79"
524601,C580604,AMAZONFEE,AMAZON FEE,-1,12/5/2011 11:35,"11,586.50",NaN,United Kingdom,"-11,586.50"
299982,A563185,B,Adjust bad debt,1,8/12/2011 14:50,"11,062.06",NaN,United Kingdom,"11,062.06"
446533,C574902,AMAZONFEE,AMAZON FEE,-1,11/7/2011 15:21,"8,286.22",NaN,United Kingdom,"-8,286.22"
173277,C551685,POST,POSTAGE,-1,5/3/2011 12:51,"8,142.75","16,029.00",United Kingdom,"-8,142.75"
173382,551697,POST,POSTAGE,1,5/3/2011 13:46,"8,142.75","16,029.00",United Kingdom,"8,142.75"
342635,C566899,AMAZONFEE,AMAZON FEE,-1,9/15/2011 13:53,"7,427.97",NaN,United Kingdom,"-7,427.97"
191386,C553355,AMAZONFEE,AMAZON FEE,-1,5/16/2011 13:58,"7,006.83",NaN,United Kingdom,"-7,006.83"
173391,C551699,M,Manual,-1,5/3/2011 14:12,"6,930.00","16,029.00",United Kingdom,"-6,930.00"
287150,C562086,AMAZONFEE,AMAZON FEE,-1,8/2/2011 12:27,"6,721.37",NaN,United Kingdom,"-6,721.37"
16357,C537652,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:51,"6,706.71",NaN,United Kingdom,"-6,706.71"
312246,C564341,AMAZONFEE,AMAZON FEE,-1,8/24/2011 14:53,"6,662.51",NaN,United Kingdom,"-6,662.51"
262414,C559917,AMAZONFEE,AMAZON FEE,-1,7/13/2011 15:21,"6,497.47",NaN,United Kingdom,"-6,497.47"

================================================================================
TOP 20 VALORES MÁS BAJOS EN UnitPrice
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
299983,A563186,B,Adjust bad debt,1,8/12/2011 14:51,"-11,062.06",NaN,United Kingdom,"-11,062.06"
299984,A563187,B,Adjust bad debt,1,8/12/2011 14:52,"-11,062.06",NaN,United Kingdom,"-11,062.06"
157195,550193,PADS,PADS TO MATCH ALL CUSHIONS,1,4/15/2011 9:27,0.00,"13,952.00",United Kingdom,0.00
279045,561226,PADS,PADS TO MATCH ALL CUSHIONS,1,7/26/2011 10:13,0.00,"15,618.00",United Kingdom,0.00
359871,568200,PADS,PADS TO MATCH ALL CUSHIONS,1,9/25/2011 14:58,0.00,"16,198.00",United Kingdom,0.00
361741,568375,BANK CHARGES,Bank Charges,1,9/26/2011 17:01,0.00,"13,405.00",United Kingdom,0.00
108088,C545478,D,Discount,-720,3/3/2011 11:08,0.01,"16,422.00",United Kingdom,-7.20
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,12/2/2010 14:23,0.03,"15,838.00",United Kingdom,-280.80
182729,C552569,D,Discount,-240,5/10/2011 12:06,0.03,"12,901.00",United Kingdom,-7.20
355050,C567903,M,Manual,-120,9/22/2011 16:29,0.03,"16,422.00",United Kingdom,-3.60
217060,555876,16045,POPART WOODEN PENCILS ASST,100,6/7/2011 15:28,0.04,"15,799.00",United Kingdom,4.00
221726,556267,16045,POPART WOODEN PENCILS ASST,500,6/9/2011 19:33,0.04,"13,694.00",United Kingdom,20.00
228959,557006,16045,POPART WOODEN PENCILS ASST,100,6/16/2011 11:29,0.04,"14,282.00",United Kingdom,4.00
229052,557009,16045,POPART WOODEN PENCILS ASST,100,6/16/2011 11:38,0.04,"14,321.00",United Kingdom,4.00
229499,557057,16045,POPART WOODEN PENCILS ASST,100,6/16/2011 14:46,0.04,"16,843.00",United Kingdom,4.00
233805,557492,16045,POPART WOODEN PENCILS ASST,100,6/20/2011 15:08,0.04,"13,717.00",United Kingdom,4.00
235392,557639,16045,POPART WOODEN PENCILS ASST,100,6/21/2011 16:13,0.04,"12,933.00",United Kingdom,4.00
243015,558389,16045,POPART WOODEN PENCILS ASST,100,6/29/2011 10:18,0.04,"14,383.00",United Kingdom,4.00
255649,559358,16045,POPART WOODEN PENCILS ASST,100,7/7/2011 19:14,0.04,"15,675.00",United Kingdom,4.00
257109,559513,16045,POPART WOODEN PENCILS ASST,100,7/8/2011 15:56,0.04,"14,534.00",United Kingdom,4.00

================================================================================
TOP 20 VALORES MÁS ALTOS EN TotalPrice
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,"16,446.00",United Kingdom,"168,469.60"
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,"12,346.00",United Kingdom,"77,183.60"
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,6/10/2011 15:28,649.50,"15,098.00",United Kingdom,"38,970.00"
15017,537632,AMAZONFEE,AMAZON FEE,1,12/7/2010 15:08,"13,541.33",NaN,United Kingdom,"13,541.33"
299982,A563185,B,Adjust bad debt,1,8/12/2011 14:50,"11,062.06",NaN,United Kingdom,"11,062.06"
173382,551697,POST,POSTAGE,1,5/3/2011 13:46,"8,142.75","16,029.00",United Kingdom,"8,142.75"
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,9/20/2011 11:05,5.06,"17,450.00",United Kingdom,"7,144.72"
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,1/11/2011 12:55,2.10,"15,749.00",United Kingdom,"6,539.40"
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,4/18/2011 13:20,2.10,"15,749.00",United Kingdom,"6,539.40"
421601,573003,23084,RABBIT NIGHT LIGHT,2400,10/27/2011 12:11,2.08,"14,646.00",Netherlands,"4,992.00"
52709,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,1/11/2011 12:55,2.55,"15,749.00",United Kingdom,"4,921.50"
467804,576365,22086,PAPER CHAIN KIT 50'S CHRISTMAS,688,11/14/2011 17:55,6.95,NaN,United Kingdom,"4,781.60"
160542,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,4/18/2011 13:20,2.40,"15,749.00",United Kingdom,"4,632.00"
52772,540818,48185,DOORMAT FAIRY CAKE,670,1/11/2011 12:57,6.75,"15,749.00",United Kingdom,"4,522.50"
297723,562955,DOT,DOTCOM POSTAGE,1,8/11/2011 10:14,"4,505.17",NaN,United Kingdom,"4,505.17"
244419,558526,23173,REGENCY TEAPOT ROSES,540,6/30/2011 11:01,8.15,"17,949.00",United Kingdom,"4,401.00"
268028,560373,M,Manual,1,7/18/2011 12:30,"4,287.63",NaN,United Kingdom,"4,287.63"
160544,550461,48185,DOORMAT FAIRY CAKE,670,4/18/2011 13:20,6.35,"15,749.00",United Kingdom,"4,254.50"
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,8/4/2011 18:06,1.45,"12,931.00",United Kingdom,"4,176.00"
422351,573077,M,Manual,1,10/27/2011 14:13,"4,161.06","12,536.00",France,"4,161.06"

================================================================================
TOP 20 VALORES MÁS BAJOS EN TotalPrice
================================================================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/9/2011 9:27,2.08,"16,446.00",United Kingdom,"-168,469.60"
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1/18/2011 10:17,1.04,"12,346.00",United Kingdom,"-77,183.60"
222681,C556445,M,Manual,-1,6/10/2011 15:31,"38,970.00","15,098.00",United Kingdom,"-38,970.00"
524602,C580605,AMAZONFEE,AMAZON FEE,-1,12/5/2011 11:36,"17,836.46",NaN,United Kingdom,"-17,836.46"
43702,C540117,AMAZONFEE,AMAZON FEE,-1,1/5/2011 9:55,"16,888.02",NaN,United Kingdom,"-16,888.02"
43703,C540118,AMAZONFEE,AMAZON FEE,-1,1/5/2011 9:57,"16,453.71",NaN,United Kingdom,"-16,453.71"
15016,C537630,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:04,"13,541.33",NaN,United Kingdom,"-13,541.33"
16356,C537651,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:49,"13,541.33",NaN,United Kingdom,"-13,541.33"
16232,C537644,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:34,"13,474.79",NaN,United Kingdom,"-13,474.79"
524601,C580604,AMAZONFEE,AMAZON FEE,-1,12/5/2011 11:35,"11,586.50",NaN,United Kingdom,"-11,586.50"
299983,A563186,B,Adjust bad debt,1,8/12/2011 14:51,"-11,062.06",NaN,United Kingdom,"-11,062.06"
299984,A563187,B,Adjust bad debt,1,8/12/2011 14:52,"-11,062.06",NaN,United Kingdom,"-11,062.06"
422375,C573079,M,Manual,-2,10/27/2011 14:15,"4,161.06","12,536.00",France,"-8,322.12"
446533,C574902,AMAZONFEE,AMAZON FEE,-1,11/7/2011 15:21,"8,286.22",NaN,United Kingdom,"-8,286.22"
173277,C551685,POST,POSTAGE,-1,5/3/2011 12:51,"8,142.75","16,029.00",United Kingdom,"-8,142.75"
342635,C566899,AMAZONFEE,AMAZON FEE,-1,9/15/2011 13:53,"7,427.97",NaN,United Kingdom,"-7,427.97"
191386,C553355,AMAZONFEE,AMAZON FEE,-1,5/16/2011 13:58,"7,006.83",NaN,United Kingdom,"-7,006.83"
173391,C551699,M,Manual,-1,5/3/2011 14:12,"6,930.00","16,029.00",United Kingdom,"-6,930.00"
287150,C562086,AMAZONFEE,AMAZON FEE,-1,8/2/2011 12:27,"6,721.37",NaN,United Kingdom,"-6,721.37"
16357,C537652,AMAZONFEE,AMAZON FEE,-1,12/7/2010 15:51,"6,706.71",NaN,United Kingdom,"-6,706.71"

In [ ]:
# ============================================================
# DETECTAR Y ELIMINAR PARES DE CORRECCIÓN / REVERSIÓN
# ------------------------------------------------------------
# Criterio:
# - una fila positiva
# - otra negativa posterior
# - mismo StockCode, Description, UnitPrice, CustomerID, Country
# - misma cantidad en valor absoluto
# - dentro de una ventana temporal configurable
# ============================================================

import pandas as pd
import numpy as np

# -------- PARÁMETRO AJUSTABLE ----------
VENTANA_HORAS = 12  # cambia a 24, 12, 72... según quieras ser más estricto o más flexible
# --------------------------------------

tmp = dfc.copy()

# Guardar índice original para poder borrar después
tmp['idx_original'] = tmp.index

# Asegurar formato datetime
tmp['InvoiceDate'] = pd.to_datetime(tmp['InvoiceDate'], errors='coerce')

# Normalización de claves para emparejar mejor
tmp['StockCode_norm'] = tmp['StockCode'].astype(str).str.strip().str.upper()
tmp['Description_norm'] = tmp['Description'].fillna('').astype(str).str.strip().str.upper()
tmp['Country_norm'] = tmp['Country'].fillna('').astype(str).str.strip().str.upper()

# CustomerID: permitir emparejar también nulos
tmp['CustomerID_norm'] = tmp['CustomerID'].astype(str).replace('nan', '__NULL__')

# Redondeo por seguridad en precios
tmp['UnitPrice_norm'] = tmp['UnitPrice'].round(2)

# Cantidad absoluta
tmp['abs_qty'] = tmp['Quantity'].abs()

# Separar positivos y negativos
pos = tmp[tmp['Quantity'] > 0].copy()
neg = tmp[tmp['Quantity'] < 0].copy()

# Renombrar para merge
pos = pos.rename(columns={
    'idx_original': 'idx_pos',
    'InvoiceDate': 'InvoiceDate_pos',
    'Quantity': 'Quantity_pos',
    'InvoiceNo': 'InvoiceNo_pos'
})

neg = neg.rename(columns={
    'idx_original': 'idx_neg',
    'InvoiceDate': 'InvoiceDate_neg',
    'Quantity': 'Quantity_neg',
    'InvoiceNo': 'InvoiceNo_neg'
})

# Claves de emparejamiento
keys = [
    'StockCode_norm',
    'Description_norm',
    'UnitPrice_norm',
    'CustomerID_norm',
    'Country_norm',
    'abs_qty'
]

# Cruce candidatos
candidatos = pos.merge(
    neg,
    on=keys,
    how='inner',
    suffixes=('_pos', '_neg')
)

# Quedarnos solo con negativos posteriores y dentro de ventana
candidatos = candidatos[
    (candidatos['InvoiceDate_neg'] > candidatos['InvoiceDate_pos']) &
    ((candidatos['InvoiceDate_neg'] - candidatos['InvoiceDate_pos']) <= pd.Timedelta(hours=VENTANA_HORAS))
].copy()

# Diferencia temporal
candidatos['delta_tiempo'] = candidatos['InvoiceDate_neg'] - candidatos['InvoiceDate_pos']

# Ordenar por cercanía temporal
candidatos = candidatos.sort_values(['idx_pos', 'delta_tiempo', 'idx_neg'])

# Emparejamiento 1 a 1:
# 1) primer negativo más cercano para cada positivo
pares = candidatos.drop_duplicates(subset='idx_pos', keep='first').copy()

# 2) asegurar que un mismo negativo no se use dos veces
pares = pares.sort_values(['idx_neg', 'delta_tiempo']).drop_duplicates(subset='idx_neg', keep='first').copy()

# Orden final
pares = pares.sort_values(['InvoiceDate_pos', 'InvoiceDate_neg']).copy()

# Resumen de pares detectados
columnas_resumen = [
    'idx_pos', 'InvoiceNo_pos', 'idx_neg', 'InvoiceNo_neg',
    'StockCode_norm', 'Description_norm',
    'Quantity_pos', 'Quantity_neg',
    'UnitPrice_norm', 'CustomerID_norm', 'Country_norm',
    'InvoiceDate_pos', 'InvoiceDate_neg', 'delta_tiempo'
]

resumen_pares = pares[columnas_resumen].copy()

print("==============================================")
print("ANÁLISIS DE PARES DE CORRECCIÓN / REVERSIÓN")
print("==============================================")
print(f"Ventana temporal usada: {VENTANA_HORAS} horas")
print(f"Pares detectados: {len(resumen_pares)}")
print(f"Filas que se eliminarán: {len(resumen_pares) * 2}")

display(resumen_pares.head(30))

# Índices a eliminar
indices_borrar = pd.Index(pares['idx_pos']).append(pd.Index(pares['idx_neg'])).unique()

# Crear dataset limpio
dfc = dfc.drop(index=indices_borrar, errors='ignore').copy()

print("\n==============================================")
print("LIMPIEZA APLICADA")
print("==============================================")
print(f"Índices eliminados: {len(indices_borrar)}")
print(f"Filas restantes en dfc: {len(dfc)}")

#comaprar df con dfc y ver cuantas lineas se han eliminado
print(f"Filas borradas tras aplicar la regla 4: {len(df) - len(dfc)}")

==============================================
ANÁLISIS DE PARES DE CORRECCIÓN / REVERSIÓN
==============================================
Ventana temporal usada: 12 horas
Pares detectados: 596
Filas que se eliminarán: 1192

,idx_pos,InvoiceNo_pos,idx_neg,InvoiceNo_neg,StockCode_norm,Description_norm,Quantity_pos,Quantity_neg,UnitPrice_norm,CustomerID_norm,Country_norm,InvoiceDate_pos,InvoiceDate_neg,delta_tiempo
65,8593,537140,8685,C537143,20685,DOORMAT RED RETROSPOT,1,-1,7.95,12748.0,UNITED KINGDOM,2010-12-05 12:53:00,2010-12-05 12:58:00,0 days 00:05:00
67,8773,537144,8952,C537157,35953,FOLKART STAR CHRISTMAS DECORATIONS,24,-24,1.25,15880.0,UNITED KINGDOM,2010-12-05 13:00:00,2010-12-05 13:09:00,0 days 00:09:00
85,11761,537298,11799,C537314,21349,IVY HEART WREATH,4,-4,6.75,13497.0,UNITED KINGDOM,2010-12-06 11:37:00,2010-12-06 11:42:00,0 days 00:05:00
91,12426,537377,12455,C537379,22865,HAND WARMER OWL DESIGN,10,-10,2.10,15882.0,UNITED KINGDOM,2010-12-06 13:01:00,2010-12-06 13:12:00,0 days 00:11:00
108,13037,537410,13042,C537413,22834,HAND WARMER BABUSHKA DESIGN,72,-72,2.10,14409.0,UNITED KINGDOM,2010-12-06 15:03:00,2010-12-06 15:07:00,0 days 00:04:00
114,14706,537609,14717,C537611,22865,HAND WARMER OWL DESIGN,36,-36,2.10,17675.0,UNITED KINGDOM,2010-12-07 13:22:00,2010-12-07 13:25:00,0 days 00:03:00
117,15017,537632,16356,C537651,AMAZONFEE,AMAZON FEE,1,-1,"13,541.33",__NULL__,UNITED KINGDOM,2010-12-07 15:08:00,2010-12-07 15:49:00,0 days 00:41:00
130,17751,537773,18351,C537820,22627,MINT KITCHEN SCALES,1,-1,8.50,16016.0,UNITED KINGDOM,2010-12-08 12:36:00,2010-12-08 14:10:00,0 days 01:34:00
157,21663,538106,21700,C538111,21830,ASSORTED CREEPY CRAWLIES,24,-24,0.42,17950.0,UNITED KINGDOM,2010-12-09 15:20:00,2010-12-09 15:24:00,0 days 00:04:00
194,24132,538313,24159,C538341,22988,SOLDIERS EGG CUP,36,-36,1.25,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
192,24130,538313,24160,C538341,22988,SOLDIERS EGG CUP,12,-12,1.25,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
191,24128,538313,24161,C538341,22976,CIRCUS PARADE CHILDRENS EGG CUP,12,-12,1.25,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
190,24127,538313,24166,C538341,22752,SET 7 BABUSHKA NESTING BOXES,96,-96,7.65,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
177,24107,538313,24167,C538341,22730,ALARM CLOCK BAKELIKE IVORY,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
187,24124,538313,24170,C538341,22729,ALARM CLOCK BAKELIKE ORANGE,4,-4,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
185,24121,538313,24171,C538341,22729,ALARM CLOCK BAKELIKE ORANGE,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
178,24108,538313,24172,C538341,22728,ALARM CLOCK BAKELIKE PINK,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
184,24115,538313,24173,C538341,22728,ALARM CLOCK BAKELIKE PINK,3,-3,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
180,24110,538313,24174,C538341,22727,ALARM CLOCK BAKELIKE RED,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
183,24113,538313,24175,C538341,22727,ALARM CLOCK BAKELIKE RED,2,-2,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
175,24105,538313,24178,C538341,22726,ALARM CLOCK BAKELIKE GREEN,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
179,24109,538313,24179,C538341,22726,ALARM CLOCK BAKELIKE GREEN,2,-2,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
181,24111,538313,24180,C538341,22726,ALARM CLOCK BAKELIKE GREEN,3,-3,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
176,24106,538313,24182,C538341,22725,ALARM CLOCK BAKELIKE CHOCOLATE,1,-1,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
186,24122,538313,24184,C538341,22725,ALARM CLOCK BAKELIKE CHOCOLATE,3,-3,3.75,15514.0,UNITED KINGDOM,2010-12-10 13:50:00,2010-12-10 14:03:00,0 days 00:13:00
196,24136,538327,24158,C538341,84380,SET OF 3 BUTTERFLY COOKIE CUTTERS,1,-1,1.25,15514.0,UNITED KINGDOM,2010-12-10 13:58:00,2010-12-10 14:03:00,0 days 00:05:00
197,24139,538327,24164,C538341,22973,CHILDREN'S CIRCUS PARADE MUG,18,-18,1.65,15514.0,UNITED KINGDOM,2010-12-10 13:58:00,2010-12-10 14:03:00,0 days 00:05:00
198,24140,538327,24165,C538341,22943,CHRISTMAS LIGHTS 10 VINTAGE BAUBLES,6,-6,4.95,15514.0,UNITED KINGDOM,2010-12-10 13:58:00,2010-12-10 14:03:00,0 days 00:05:00
199,24147,538327,24186,C538341,22621,TRADITIONAL KNITTING NANCY,48,-48,1.25,15514.0,UNITED KINGDOM,2010-12-10 13:58:00,2010-12-10 14:03:00,0 days 00:05:00
200,24148,538327,24187,C538341,22586,FELTCRAFT HAIRBAND PINK AND BLUE,1,-1,0.85,15514.0,UNITED KINGDOM,2010-12-10 13:58:00,2010-12-10 14:03:00,0 days 00:05:00

==============================================
LIMPIEZA APLICADA
==============================================
Índices eliminados: 1192
Filas restantes en dfc: 532939
Filas borradas tras aplicar la regla 4: 8970

In [ ]:
# ============================================================
# DATASET SOLO DEVOLUCIONES (solo InvoiceNo con C)
# ------------------------------------------------------------
# Se conservan únicamente las filas cuyo InvoiceNo empieza por C.
# CustomerID nulo se conserva.
# ============================================================

mask_devoluciones = dfc['InvoiceNo'].astype(str).str.startswith('C', na=False)

print(f"Filas de devoluciones / credit notes con InvoiceNo 'C': {mask_devoluciones.sum()}")

dfc_devoluciones = dfc[mask_devoluciones].copy()

print(f"Filas restantes en dataset solo devoluciones: {len(dfc_devoluciones)}")
print(f"Filas excluidas respecto a dfc: {len(dfc) - len(dfc_devoluciones)}")

Filas de devoluciones / credit notes con InvoiceNo 'C': 8655
Filas restantes en dataset solo devoluciones: 8655
Filas excluidas respecto a dfc: 524284

In [ ]:
# ============================================================
# REVISIÓN Y ELIMINACIÓN DE LÍNEAS NO ASOCIADAS A PRODUCTO REAL
# ============================================================

descripciones_excluir = [
    'POSTAGE',
    'DOTCOM POSTAGE',
    'MANUAL',
    'CARRIAGE',
    'AMAZON FEE',
    'ADJUST BAD DEBT',
    'BANK CHARGES',
    'DISCOUNT',
    'SAMPLES',
    'CRUK COMMISSION'
]

desc_norm = dfc_devoluciones['Description'].astype(str).str.strip().str.upper()
mask_no_producto = desc_norm.isin(descripciones_excluir)

print("Conteo por descripción antes de eliminar:")
display(desc_norm[mask_no_producto].value_counts())

print(f"\nFilas a eliminar: {mask_no_producto.sum()}")

dfc_devoluciones = dfc_devoluciones[~mask_no_producto].copy()


print(f"Filas restantes: {len(dfc_devoluciones)}")
print(f"Filas borradas: {len(df) - len(dfc_devoluciones)}")

Conteo por descripción antes de eliminar:

Description
MANUAL             216
POSTAGE            120
DISCOUNT            77
SAMPLES             60
AMAZON FEE          30
BANK CHARGES        25
CRUK COMMISSION     16
CARRIAGE             2
DOTCOM POSTAGE       1
Name: count, dtype: int64

Filas a eliminar: 547
Filas restantes: 8108
Filas borradas: 533801

In [ ]:
# Identificar filas con Quantity <= 0 en el DataFrame limpio (dfc)
print("\n--- Filas con 'Quantity' menor o igual a cero en dfc ---")
quantity_no_positiva_dfc = dfc[dfc['Quantity'] <= 0]
print(f"Número de registros con Quantity <= 0 en dfc: {len(quantity_no_positiva_dfc)}")
if not quantity_no_positiva_dfc.empty:
    print("Se encontraron los siguientes registros anómalos:")
    display(quantity_no_positiva_dfc)
else:
    print("No se encontraron filas con 'Quantity' menor o igual a cero en dfc.")

# Identificar filas con UnitPrice <= 0 en el DataFrame limpio (dfc)
print("\n--- Filas con 'UnitPrice' menor o igual a cero en dfc ---")
unitprice_no_positivo_dfc = dfc[dfc['UnitPrice'] <= 0]
print(f"Número de registros con UnitPrice <= 0 en dfc: {len(unitprice_no_positivo_dfc)}")
if not unitprice_no_positivo_dfc.empty:
    print("Se encontraron los siguientes registros anómalos:")
    display(unitprice_no_positivo_dfc)
else:
    print("No se encontraron filas con 'UnitPrice' menor o igual a cero en dfc.")

--- Filas con 'Quantity' menor o igual a cero en dfc ---
Número de registros con Quantity <= 0 en dfc: 8108
Se encontraron los siguientes registros anómalos:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,"15,311.00",United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,"17,548.00",United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96
...,...,...,...,...,...,...,...,...,...
540448,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,12/9/2011 9:57,1.95,"14,397.00",United Kingdom,-23.40
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/9/2011 9:57,0.83,"14,397.00",United Kingdom,-9.13
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/9/2011 11:57,10.95,"15,311.00",United Kingdom,-54.75
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/9/2011 11:58,1.25,"17,315.00",United Kingdom,-1.25
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,12/9/2011 11:58,1.25,"17,315.00",United Kingdom,-6.25

--- Filas con 'UnitPrice' menor o igual a cero en dfc ---
Número de registros con UnitPrice <= 0 en dfc: 0
No se encontraron filas con 'UnitPrice' menor o igual a cero en dfc.

In [ ]:
dfc_devoluciones.to_csv("data_ramon_v04_regresion_devoluciones.csv", index=False)

from google.colab import files
files.download("data_ramon_v04_regresion_devoluciones.csv")

In [ ]:
dfc_devoluciones.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,"15,311.00",United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,"17,548.00",United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,"17,548.00",United Kingdom,-6.96